name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload JAR to S3
        run: |
          aws s3 cp target/*.jar s3://elasticbeanstalk-us-east-2-010430189416/${{ github.sha }}.jar

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment --application-name myblog-v1 \
            --environment-name Myblog-v1-env-2 \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket="elasticbeanstalk-us-east-2-010430189416",S3Key="${{ github.sha }}.jar"
